version: '3'
services:
  app:
    image: ${DOCKER_HUB_USERNAME}/hyundai-sopkathon36-web4
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${MYSQL_DB_URL}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app