version: '3'
services:
  app:
    image: ${DOCKER_HUB_USERNAME}/hyundai-sopkathon36-web4
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_DB_HOST: ${MYSQL_DB_HOST}
      MYSQL_DB_PORT: ${MYSQL_DB_PORT}
      MYSQL_DB_USER: ${MYSQL_DB_USER}
      MYSQL_DB_PASS: ${MYSQL_DB_PASS}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app